[package]
name = "coacd"
version = "0.1.0"
edition = "2024"

[dependencies]
glam = { version = "0.29", features = ["approx"] }
spade = "2.15"
obvhs = "0.2"
hashbrown = "0.16"
foldhash = "0.2"

[dev-dependencies]
# For test scenes and rendering
bevy = { version = "0.16" }
